# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DS Flashcard Guide
email: maorninja@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  The complete guide to getting your flashcard setup.
twitter_username: username
github_username: username
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "Source Code"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NightYoshi370/mm-github-pages-starter"
    - label: "Credits"
      icon: "fab fa-fw fa-community"
      url: "/credits"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar: false
  - scope:
      path: "_pages/af_ZA"
      type: pages
    values:
      permalink: /af_ZA/:basename:output_ext
      lang: af
  - scope:
      path: "_pages/ar_SA"
      type: pages
    values:
      permalink: /ar_SA/:basename:output_ext
      lang: ar
  - scope:
      path: "_pages/ca_ES"
      type: pages
    values:
      permalink: /ca_ES/:basename:output_ext
      lang: ca
  - scope:
      path: "_pages/cs_CZ"
      type: pages
    values:
      permalink: /cs_CZ/:basename:output_ext
      lang: cs
  - scope:
      path: "_pages/da_DK"
      type: pages
    values:
      permalink: /da_DK/:basename:output_ext
      lang: da
  - scope:
      path: "_pages/de_DE"
      type: pages
    values:
      permalink: /de_DE/:basename:output_ext
      lang: ds
  - scope:
      path: "_pages/el_GR"
      type: pages
    values:
      permalink: /el_GR/:basename:output_ext
      lang: el
  - scope:
      path: "_pages/en_PT"
      type: pages
    values:
      permalink: /en_PT/:basename:output_ext
      lang: en-PT
  - scope:
      path: "_pages/en_US"
      type: pages
    values:
      permalink: /:basename:output_ext
      lang: en
  - scope:
      path: "_pages/es_ES"
      type: pages
    values:
      permalink: /es_ES/:basename:output_ext
      lang: es
  - scope:
      path: "_pages/fi_FI"
      type: pages
    values:
      permalink: /fi_FI/:basename:output_ext
      lang: fi
  - scope:
      path: "_pages/fr_FR"
      type: pages
    values:
      permalink: /fr_FR/:basename:output_ext
      lang: fr
  - scope:
      path: "_pages/he_IL"
      type: pages
    values:
      permalink: /he_IL/:basename:output_ext
      lang: he
  - scope:
      path: "_pages/hu_HU"
      type: pages
    values:
      permalink: /hu_HU/:basename:output_ext
      lang: hu
  - scope:
      path: "_pages/id_ID"
      type: pages
    values:
      permalink: /id_ID/:basename:output_ext
      lang: id
  - scope:
      path: "_pages/it_IT"
      type: pages
    values:
      permalink: /it_IT/:basename:output_ext
      lang: it
  - scope:
      path: "_pages/ja_JP"
      type: pages
    values:
      permalink: /ja_JP/:basename:output_ext
      lang: ja
  - scope:
      path: "_pages/ko_KR"
      type: pages
    values:
      permalink: /ko_KR/:basename:output_ext
      lang: ko
  - scope:
      path: "_pages/ms_MY"
      type: pages
    values:
      permalink: /ms_MY/:basename:output_ext
      lang: ms
  - scope:
      path: "_pages/no_NO"
      type: pages
    values:
      permalink: /no_NO/:basename:output_ext
      lang: no-NO
  - scope:
      path: "_pages/nl_NL"
      type: pages
    values:
      permalink: /nl_NL/:basename:output_ext
      lang: nl
  - scope:
      path: "_pages/pl_PL"
      type: pages
    values:
      permalink: /pl_PL/:basename:output_ext
      lang: pl
  - scope:
      path: "_pages/pt_BR"
      type: pages
    values:
      permalink: /pt_BR/:basename:output_ext
      lang: pt-BR
  - scope:
      path: "_pages/pt_PT"
      type: pages
    values:
      permalink: /pt_PT/:basename:output_ext
      lang: pt-PT
  - scope:
      path: "_pages/ro_RO"
      type: pages
    values:
      permalink: /ro_RO/:basename:output_ext
      lang: ro
  - scope:
      path: "_pages/ru_RU"
      type: pages
    values:
      permalink: /ru_RU/:basename:output_ext
      lang: ru
  - scope:
      path: "_pages/sr_SP"
      type: pages
    values:
      permalink: /sr_SP/:basename:output_ext
      lang: sr
  - scope:
      path: "_pages/sv_SE"
      type: pages
    values:
      permalink: /sv_SE/:basename:output_ext
      lang: sv
  - scope:
      path: "_pages/th_TH"
      type: pages
    values:
      permalink: /th_TH/:basename:output_ext
      lang: th
  - scope:
      path: "_pages/tr_TR"
      type: pages
    values:
      permalink: /tr_TR/:basename:output_ext
      lang: tr
  - scope:
      path: "_pages/uk_UA"
      type: pages
    values:
      permalink: /uk_UA/:basename:output_ext
      lang: uk
  - scope:
      path: "_pages/vi_VN"
      type: pages
    values:
      permalink: /vi_VN/:basename:output_ext
      lang: vi
  - scope:
      path: "_pages/zh_CN"
      type: pages
    values:
      permalink: /zh_CN/:basename:output_ext
      lang: zh-Hans
  - scope:
      path: "_pages/zh_TW"
      type: pages
    values:
      permalink: /zh_TW/:basename:output_ext
      lang: zh-Hant
  - scope:
      path: "_pages/af_ZA/home.md"
      type: pages
    values:
      permalink: /af_ZA/index:output_ext
  - scope:
      path: "_pages/ar_SA/home.md"
      type: pages
    values:
      permalink: /ar_SA/index:output_ext
  - scope:
      path: "_pages/ca_ES/home.md"
      type: pages
    values:
      permalink: /ca_ES/index:output_ext
  - scope:
      path: "_pages/cs_CZ/home.md"
      type: pages
    values:
      permalink: /cs_CZ/index:output_ext
  - scope:
      path: "_pages/da_DK/home.md"
      type: pages
    values:
      permalink: /da_DK/index:output_ext
  - scope:
      path: "_pages/de_DE/home.md"
      type: pages
    values:
      permalink: /de_DE/index:output_ext
  - scope:
      path: "_pages/el_GR/home.md"
      type: pages
    values:
      permalink: /el_GR/index:output_ext
  - scope:
      path: "_pages/en_PT/home.md"
      type: pages
    values:
      permalink: /en_PT/index:output_ext
  - scope:
      path: "_pages/en_US/home.md"
      type: pages
    values:
      permalink: /index:output_ext
  - scope:
      path: "_pages/es_ES/home.md"
      type: pages
    values:
      permalink: /es_ES/index:output_ext
  - scope:
      path: "_pages/fi_FI/home.md"
      type: pages
    values:
      permalink: /fi_FI/index:output_ext
  - scope:
      path: "_pages/fr_FR/home.md"
      type: pages
    values:
      permalink: /fr_FR/index:output_ext
  - scope:
      path: "_pages/he_IL/home.md"
      type: pages
    values:
      permalink: /he_IL/index:output_ext
  - scope:
      path: "_pages/hu_HU/home.md"
      type: pages
    values:
      permalink: /hu_HU/index:output_ext
  - scope:
      path: "_pages/id_ID/home.md"
      type: pages
    values:
      permalink: /id_ID/index:output_ext
  - scope:
      path: "_pages/it_IT/home.md"
      type: pages
    values:
      permalink: /it_IT/index:output_ext
  - scope:
      path: "_pages/ja_JP/home.md"
      type: pages
    values:
      permalink: /ja_JP/index:output_ext
  - scope:
      path: "_pages/ko_KR/home.md"
      type: pages
    values:
      permalink: /ko_KR/index:output_ext
  - scope:
      path: "_pages/ms_MY/home.md"
      type: pages
    values:
      permalink: /ms_MY/index:output_ext
  - scope:
      path: "_pages/no_NO/home.md"
      type: pages
    values:
      permalink: /no_NO/index:output_ext
  - scope:
      path: "_pages/nl_NL/home.md"
      type: pages
    values:
      permalink: /nl_NL/index:output_ext
  - scope:
      path: "_pages/pl_PL/home.md"
      type: pages
    values:
      permalink: /pl_PL/index:output_ext
  - scope:
      path: "_pages/pt_BR/home.md"
      type: pages
    values:
      permalink: /pt_BR/index:output_ext
  - scope:
      path: "_pages/pt_PT/home.md"
      type: pages
    values:
      permalink: /pt_PT/index:output_ext
  - scope:
      path: "_pages/ro_RO/home.md"
      type: pages
    values:
      permalink: /ro_RO/index:output_ext
  - scope:
      path: "_pages/ru_RU/home.md"
      type: pages
    values:
      permalink: /ru_RU/index:output_ext
  - scope:
      path: "_pages/sr_SP/home.md"
      type: pages
    values:
      permalink: /sr_SP/index:output_ext
  - scope:
      path: "_pages/sv_SE/home.md"
      type: pages
    values:
      permalink: /sv_SE/index:output_ext
  - scope:
      path: "_pages/th_TH/home.md"
      type: pages
    values:
      permalink: /th_TH/index:output_ext
  - scope:
      path: "_pages/tr_TR/home.md"
      type: pages
    values:
      permalink: /tr_TR/index:output_ext
  - scope:
      path: "_pages/uk_UA/home.md"
      type: pages
    values:
      permalink: /uk_UA/index:output_ext
  - scope:
      path: "_pages/vi_VN/home.md"
      type: pages
    values:
      permalink: /vi_VN/index:output_ext
  - scope:
      path: "_pages/zh_CN/home.md"
      type: pages
    values:
      permalink: /zh_CN/index:output_ext
  - scope:
      path: "_pages/zh_TW/home.md"
      type: pages
    values:
      permalink: /zh_TW/index:output_ext
